theme: jekyll-theme-slate
title: [Yuta Nakano's page]
description: [Affiliation: Knowledge Base Laboratory,
Division of Computer Science and Information Technology,
Graduate School of Information Science and Technology, Hokkaido University.]
